name: Teste Lembrete de Água via Telegram

on:
  schedule:
    # 22:13 no Brasil (UTC-3) equivale a 01:13 UTC
    - cron: '13 1 * * *'
  workflow_dispatch: # Permite disparar manualmente na aba Actions para testar imediatamente

jobs:
  enviar-lembrete:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar bibliotecas
        run: pip install requests schedule

      - name: Executar script Python
        run: python bot.py
