name: Teste Lembrete de Água via Telegram

on:
  schedule:
    # 22:30 no Brasil (UTC-3) equivale a 01:30 UTC
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  enviar-lembrete:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar bibliotecas
        run: pip install requests

      - name: Executar script Python
        run: python bot.py
